# CDeath plugin config
# If you have any questions feel free to ask them on discord (MuchoMore#0717)

# Few messages contains placeholder "%player%" that replaces himself with name of player that killed sm1/revived sm1 or was revived/knocked sm1
# If you set action value to true and forgot to add or add corupted value this might happen:
# - if its sound:
#   -null value = no sound will be played
#   -wrong value = ENTITY_PLAYER_BURP sound will be played
# - if its message
#   -null value = no message will be sent
#
#  PERMISSIONS
#
#  cdeath.*:
#    description: Grants all permissions
#  cdeath.reload:
#    description: Grants ability to reload config
#  cdeath.help:
#    description: Grants ability to see help info
#  cdeath.give:
#    description: Grants ability to give revive item
#  cdeath.reviveall:
#    description: Grants ability to revive all dead players
#  cdeath.disable:
#    description: Grants ability to disable plugin
#  cdeath.revive:
#    description: Grants ability to revive player
#  cdeath.freeze:
#    description: Grants ability to put player into freeze state
#  cdeath.smash:
#    description: Grants ability to smash player
#
#
data:
  #Seconds after which player corpse will be removed and player killed
  deathTimer: 60
  #Hologram displayed above player that was killed
  hologramName: '&6Im dead &4%player%'
  #Material of revive item
  reviveItemMaterial: 'GOLDEN_APPLE'
  #Name of revive item
  reviveItemName: 'Reviver3000'
  #Lore of revive item
  reviveItemLore:
    - 'Some'
    - 'Lore'
  #True = Sends message to player after reciving revive item
  messageOnReceiveItemEnable: true
  #Message that's send after reciving revive item
  messageOnReceiveItem: 'You received an item'
  #True = sound will be played on reciving revive item
  soundOnReceiveItemEnabled: true
  #Sound played on reciving item
  soundOnReceiveItem: 'ENTITY_PLAYER_BURP'
  #Disable spam in console if reviving item is done for multiple players at once
  messageOnGivingItemEnable: true

  #True = Plays sound when player is reviving other player
  soundOnRevivingSm1Enabled: true
  #Sound played when reviving someone
  soundOnRevivingSm1: 'ENTITY_PLAYER_BURP'
  #True = Plays sound after being revived by someone
  soundOnBeingRevivedEnabled: true
  #Sound played when being revived
  soundOnBeingRevived: 'ENTITY_PLAYER_BURP'
  #True = Sends message after player revive other player
  messageOnRevivingSm1Enabled: true
  #Message sent to player that revives other %player%
  messageOnRevivingSm1: 'You have revived %player%'
  #True = Sends message to player that is revived
  messageOnBeingRevivedEnabled: true
  #Message send to revied player containing reviver name (%player%)
  messageOnBeingRevived: 'You were revived by %player%'
  #True = Sends message to player after he gets killed for the second time or no one revived him
  messageOnSmashEnabled: true
  #Message sent after being smashed
  messageOnSmash: 'No one revived you, u are now dead for good'
  #True = Plays sound on being smashed
  soundOnSmashEnabled: true
  #Sound on being smashed
  soundOnSmash: 'ENTITY_PLAYER_BURP'
  #True = sets player health after revive
  setHealthOnReviveEnabled: true
  #Health value after revive
  setHealthOnRevive: 20
  #True = Sets player food lvl after revive
  setFoodLvlOnReviveEnabled: true
  #Food lvl value after revive
  setFoodLvlOnRevive: 20
  #True = Apply effect to player after revive
  effectsOnReviveEnabled: true
  # To add another effect simply create:
  #   effect_NameThatWasntMentionBefore
  #     name: 'EffectName'
  #     dur_seconds: Duration in seconds
  #     amplifier: How strong should effect be (jump 1, 2, 3 etc.)
  #
  effectsOnRevive:
    effectOne:
      name: "HEAL"
      dur_seconds: 20
      amplifier: 1
    effectTwo:
      name: "HEAL"
      dur_seconds: 20
      amplifier: 1
    effectThree:
      name: "HEAL"
      dur_seconds: 20
      amplifier: 1
  #True = sends message to player after knockup
  messageOnFreezeEnabled: true
  #Message sent after knockup, containing name of player/entity that killed player (%player%)
  messageOnFreeze: 'You were grounded by %player%'
  #True = plays sound after knockup
  soundOnFreezeEnabled: true
  #Sound value after knockup
  soundOnFreeze: 'ENTITY_GHAST_SCREAM'